// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql"
)

type File struct {
	ID       string
	ThreadID sql.NullString
	Name     string
	Size     int64
	Content  []byte
}

type Thread struct {
	ID       string
	WorkerID sql.NullString
	Name     string
	FileType string
}

type Worker struct {
	ID          string
	Name        string
	Description sql.NullString
}
